In [ ]:
import numpy as np

# Define two tensors (2D arrays)
tensor_a = np.array([[1, 2, 3],
                      [4, 5, 6]])

tensor_b = np.array([[7, 8, 9],
                      [10, 11, 12]])

In [5]:
# Element-wise addition
addition = tensor_a + tensor_b
print(f"{'Tensor A':^10} + {'Tensor B':^10} = {'Addition':^10}")
print(f"{tensor_a}\n + \n{tensor_b}\n = \n{addition}\n")

 Tensor A  +  Tensor B  =  Addition 
[[1 2 3]
 [4 5 6]]
 + 
[[ 7  8  9]
 [10 11 12]]
 = 
[[ 8 10 12]
 [14 16 18]]



In [6]:
# Element-wise subtraction
subtraction = tensor_a - tensor_b
print(f"{'Tensor A':^10} - {'Tensor B':^10} = {'Subtraction':^10}")
print(f"{tensor_a}\n - \n{tensor_b}\n = \n{subtraction}\n")

 Tensor A  -  Tensor B  = Subtraction
[[1 2 3]
 [4 5 6]]
 - 
[[ 7  8  9]
 [10 11 12]]
 = 
[[-6 -6 -6]
 [-6 -6 -6]]



In [7]:
# Element-wise multiplication
multiplication = tensor_a * tensor_b
print(f"{'Tensor A':^10} * {'Tensor B':^10} = {'Multiplication':^10}")
print(f"{tensor_a}\n * \n{tensor_b}\n = \n{multiplication}\n")

 Tensor A  *  Tensor B  = Multiplication
[[1 2 3]
 [4 5 6]]
 * 
[[ 7  8  9]
 [10 11 12]]
 = 
[[ 7 16 27]
 [40 55 72]]



In [8]:
# Element-wise division
division = tensor_a / tensor_b
print(f"{'Tensor A':^10} / {'Tensor B':^10} = {'Division':^10}")
print(f"{tensor_a}\n / \n{tensor_b}\n = \n{division}\n")

 Tensor A  /  Tensor B  =  Division 
[[1 2 3]
 [4 5 6]]
 / 
[[ 7  8  9]
 [10 11 12]]
 = 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

